version: '3'
services:
  elasticsearch:
    image: khezen/elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    environment:
      - NODE_NAME=elasticsearch
  logstash:
    build: logstash/
    depends_on:
      - elasticsearch
    ports:
      - '5000:5000/udp'
      - '5001:5001'
      - '5044:5044'
    volumes:
      - './elasticsearch/config:/etc/elasticsearch:ro'
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USER=elastic
      - LOGSTASH_PWD=changeme
      - TS_PWD=changeme
    command: logstash -f /etc/logstash/conf.d/
  kibana:
    image: 'khezen/kibana:5'
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    volumes:
      - './elasticsearch/config:/etc/elasticsearch:ro'
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - LOGSPOUT=ignore
  logspout:
    image: gliderlabs/logspout:master
    depends_on:
      - logstash
    ports:
      - 8100:8000
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: syslog://logstash:5000
  metricbeat:
    build: metricbeat/
    depends_on:
      - logstash
    volumes:
      - '/proc:/hostfs/proc:ro'
      - '/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro'
      - '/:/hostfs:ro'
    environment:
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
      - KIBANA_HOST=kibana
      - KIBANA_PORT=5601
      - KIBANA_PWD=changeme
    command: metricbeat -e -system.hostfs=/hostfs
  purger:
    build: purger/
    depends_on:
      - elasticsearch
    volumes:
      - ./elasticsearch/config:/etc/elasticsearch
    environment:
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
      - ELASTIC_USER=elastic
      - ELASTIC_PASS=changeme
    command: echo "purger is disabled for local development"
