kibanabox:
  build: kibanabox
#  image: dddecaf/kibanabox:e65ffb06159b
  ports:
    - 5601:5601
  command: http://app.dd-decaf.eu:9200
  environment:
    - LOGSPOUT=ignore
logbox:
  build: logstash
#  image: dddecaf/logstashgst:e65ffb06159b
  ports:
    - 6666:5000/udp
    - 9200:9200
  environment:
    - LOGSPOUT=ignore
logspout:
  image: gliderlabs/logspout:master
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - 8100:8000
  command: syslog://app.dd-decaf.eu:6666