version: '3'
services:
  elasticsearch:
    image: khezen/elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    environment:
      - NODE_NAME=elasticsearch
  logstash:
    build: logstash/
    depends_on:
      - elasticsearch
    ports:
      - '6666:5000/udp'
      - '5001:5001'
      - '5044'
    volumes:
      - './elasticsearch/config:/etc/elasticsearch:ro'
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USER=elastic
      - LOGSTASH_PWD=changeme
      - TS_PWD=changeme
    command: logstash -f /etc/logstash/conf.d/
  kibana:
    image: 'khezen/kibana:5'
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    volumes:
      - './elasticsearch/config:/etc/elasticsearch:ro'
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - LOGSPOUT=ignore
  logspout:
    image: gliderlabs/logspout:master
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - 8100:8000
    command: syslog://app.dd-decaf.eu:6666
