metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']

- module: system
  period: 60s
  metricsets: [filesystem, fsstat]
  filters:
    - drop_event.when.regexp.mount_point: '^(/hostfs)?/(sys|cgroup|proc|dev|etc|host|var/lib/docker)($|/)'

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ["https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
  username: "${ELASTICSEARCH_USER}"
  password: "${ELASTICSEARCH_PWD}"
  ssl.certificate_authorities: ["/etc/elasticsearch/searchguard/ssl/beats.all.pem"]
  ssl.certificate: "/etc/elasticsearch/searchguard/ssl/beats-signed.pem"
  ssl.key: "/etc/elasticsearch/searchguard/ssl/beats.key.pem"

setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  username: "kibana" 
  password: "${KIBANA_PWD}"

setup.dashboards.enabled: true
