metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']

- module: system
  period: 60s
  metricsets: [filesystem, fsstat]
  filters:
    - drop_event.when.regexp.mount_point: '^(/hostfs)?/(sys|cgroup|proc|dev|etc|host|var/lib/docker)($|/)'

processors:
- add_cloud_metadata:

output.logstash:
  hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]

setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  username: "kibana" 
  password: "${KIBANA_PWD}"

setup.dashboards.enabled: true
